#!/usr/bin/env bash

set -e

function print_version() {
    echo "Adafruit Pi External Root Helper v0.0.1"
    exit 1
}

function print_help() {
    echo "Usage: $0 -d [target device]"
    echo "    -h            Print this help"
    echo "    -v            Print version information"
    echo "    -d [device]   Specify path of device to convert to root"
    echo
    echo "You must specify a device."
    exit 1
}

function bail() {
    FG="1;31m"
    BG="40m"
    echo -en "[\033[${FG}\033[${BG}error\033[0m] "
    echo "$*"
    exit 1
}

function info() {
    task="$1"
    shift
    FG="1;32m"
    BG="40m"
    echo -e "[\033[${FG}\033[${BG}${task}\033[0m] $*"
}

if [[ $EUID -ne 0 ]]; then
    bail "must be run as root. try: sudo adafruit-pi-externalroot-helper"
fi

args=$(getopt -uo 'hvd:' -- $*)
[ $? != 0 ] && print_help
set -- $args

for i
do
    case "$i"
    in
        -h)
            print_help
            ;;
        -v)
            print_version
            ;;
        -d)
            target_drive="$2"
            echo "Target drive = ${2}"
            shift
            shift
            ;;
    esac
done

if [[ ! -e "$target_drive" ]]; then
    bail "Target drive ${target_drive} must be an existing device (use -d /dev/foo to specify)"
fi

info "start" "Will create new ext4 filesystem on ${target_drive}"
info "start" "If there is data on ${target_drive}, it will be lost."
read -p "Really proceed? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "Quitting."
    exit
fi

info "dependencies" "Installing gdisk, rsync, and pv."
    apt-get install gdisk rsync pv

export target_partition="${target_drive}1"

info "fs create" "Creating ${target_partition}"
    parted --script "${target_drive}" mklabel gpt
    parted --script --align optimal "${target_drive}" mkpart primary ext4 0% 100%

info "fs create" "Creating ext4 filesystem on ${target_partition}"
    mkfs -t ext4 -L rootfs "${target_partition}"

info "fs id" "Getting UUID for target partition"
    eval `blkid -o export "${target_partition}"`
    export target_partition_uuid=$UUID

info "fs id" "Getting Partition unique GUID for target filesystem"
    export partition_unique_guid=`echo 'i' | sudo gdisk /dev/sda | grep 'Partition unique GUID:' | awk '{print $4}'`

info "fs id" "Target partition UUID: ${target_partition_uuid}"
info "fs id" "Partition unique GUID: ${partition_unique_guid}"

info "fs copy" "Mounting ${target_partition} on /mnt"
    mount "${target_partition}" /mnt

info "fs copy" "Copying root filesystem to ${target_partition}"
    rsync -ax / /mnt

info "boot config" "Configuring boot from {$target_partition}"
    cp /boot/cmdline.txt /boot/cmdline.txt.bak
    sed -i "s|root=\/dev\/mmcblk0p2|root=PARTUUID=${partition_unique_guid} rootdelay=5|" /boot/cmdline.txt

info "boot config" "Commenting out old root partition in /etc/fstab, adding new one"
    sed -i '/mmcblk0p2/s/^/#/' /mnt/etc/fstab
    echo "/dev/disk/by-uuid/${target_partition_uuid}    /   ext4    defaults,noatime  0       1" >> /mnt/etc/fstab
    cat /etc/fstab

info "boot config" "Ok, your system should be ready. You may wish to check:"
info "boot config" "  /mnt/etc/fstab"
info "boot config" "  /boot/cmdline.txt"
info "boot config" "Your new root drive is currently accessible under /mnt."
info "boot config" "In order to restart with this drive at /, please type:"
info "boot config" "sudo reboot"
